version: "3"

services:
  app:
    build: .
    environment:
      MONGO_URL: "mongodb://mongoserver:27017/test"
    depends_on:
      - mongoserver
    ports:
      - "3000-3010:3000"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules

  mongoserver:
    image: mongo
